export const REQUEST_TYPE_KEYWORDS: { rt: string; keywords: string[] }[] = [
  {
    rt: "ABM-ARMOURED CAR - TECH MEET",
    keywords: [
      "armoured car",
      "armored car",
      "tech meet",
      "technical meeting",
      "cash replenishment",
      "cash delivery",
      "cash collection",
      "armoured vehicle",
      "security vehicle",
      "abm technician",
      "atm technician",
      "tech visit",
    ],
  },
  {
    rt: "ABM-MACHINE - DOWN",
    keywords: [
      "abm down",
      "atm down",
      "machine down",
      "abm not working",
      "atm not working",
      "abm out of service",
      "atm out of service",
      "not dispensing",
      "abm offline",
      "atm offline",
      "abm broken",
      "atm broken",
      "cash machine broken",
      "abm error",
      "atm error",
      "abm screen black",
      "abm unresponsive",
    ],
  },
  {
    rt: "ABM-MACHINE-CLEANING",
    keywords: [
      "abm cleaning",
      "atm cleaning",
      "clean abm",
      "clean atm",
      "abm dirty",
      "atm dirty",
      "abm machine dirty",
      "abm hygiene",
      "atm hygiene",
      "abm sanitize",
      "atm sanitize",
    ],
  },
  {
    rt: "ABM-SECURITY EQUIP - COMBS SCRAMBLED",
    keywords: [
      "combs scrambled",
      "combination scrambled",
      "combo scrambled",
      "security combination",
      "lock combination",
      "combination reset",
      "abm combination",
      "abm security",
      "scrambled combination",
      "access combination",
      "safe combination scrambled",
    ],
  },
  {
    rt: "ABM-SURROUNDS-LIGHTS",
    keywords: [
      "abm lights",
      "atm lights",
      "surround lighting",
      "abm area lighting",
      "atm area lighting",
      "light near abm",
      "light near atm",
      "abm light out",
      "atm light out",
      "kiosk lighting",
    ],
  },
  {
    rt: "ABM-SURROUNDS-OTHER",
    keywords: [
      "abm surrounds",
      "atm surrounds",
      "area around abm",
      "area around atm",
      "abm kiosk",
      "atm kiosk",
      "abm enclosure",
      "atm enclosure",
      "abm area",
      "atm area",
      "abm surroundings",
    ],
  },
  {
    rt: "ABM-SURROUNDS-SIGNS",
    keywords: [
      "abm signs",
      "atm signs",
      "abm signage",
      "atm signage",
      "sign missing near abm",
      "sign damaged near atm",
      "abm poster",
      "atm poster",
      "abm label",
      "surround signs",
      "kiosk sign",
    ],
  },
  {
    rt: "ABM-SURROUNDS-WASTE",
    keywords: [
      "abm waste",
      "atm waste",
      "garbage near abm",
      "garbage near atm",
      "litter near abm",
      "litter near atm",
      "trash near abm",
      "trash near atm",
      "abm area dirty",
      "atm area dirty",
      "waste around abm",
    ],
  },
  {
    rt: "AIR QUALITY",
    keywords: [
      "air quality",
      "poor air quality",
      "bad air",
      "stale air",
      "stuffy",
      "fumes",
      "smoke",
      "co2",
      "carbon dioxide",
      "carbon monoxide",
      "air pollution",
      "toxic smell",
      "chemical smell",
      "gas smell",
      "ventilation problem",
      "no fresh air",
      "musty",
      "mould smell",
      "mold smell",
    ],
  },
  {
    rt: "APPLIANCES - NEW",
    keywords: [
      "new appliance",
      "appliance request",
      "new fridge",
      "new refrigerator",
      "new microwave",
      "new kettle",
      "new coffee machine",
      "new dishwasher",
      "new toaster",
      "new water heater",
      "request appliance",
      "additional appliance",
      "need appliance",
      "appliance needed",
    ],
  },
  {
    rt: "APPLIANCES - REPAIR",
    keywords: [
      "appliance repair",
      "appliance broken",
      "fridge broken",
      "fridge not working",
      "refrigerator broken",
      "microwave broken",
      "microwave not working",
      "dishwasher broken",
      "dishwasher not working",
      "kettle broken",
      "coffee machine broken",
      "appliance malfunction",
      "appliance fault",
      "toaster broken",
      "water heater broken",
    ],
  },
  {
    rt: "AWARENESS-PROGRAM",
    keywords: [
      "awareness program",
      "awareness campaign",
      "energy efficiency",
      "ee program",
      "ee awareness",
      "training program",
      "sustainability program",
      "green initiative",
      "energy saving",
      "energy awareness",
    ],
  },
  {
    rt: "BLINDS - TENANT - BLIND CLEANING",
    keywords: [
      "blind cleaning",
      "blinds dirty",
      "clean blinds",
      "window blinds",
      "venetian blind",
      "roller blind",
      "blind repair",
      "blinds not working",
      "blind stuck",
      "blind broken",
      "window covering",
      "blinds dusty",
    ],
  },
  {
    rt: "BOTTLED WATER",
    keywords: [
      "bottled water",
      "water delivery",
      "water cooler",
      "drinking water",
      "water dispenser",
      "water refill",
      "water bottle",
      "water supply",
      "no drinking water",
      "water station",
      "water cooler empty",
    ],
  },
  {
    rt: "BUILDING-ENVELOP-C",
    keywords: [
      "caulking",
      "sealant",
      "building envelope",
      "seal",
      "sealing",
      "gap in wall",
      "crack in wall",
      "draft from wall",
      "cracked seal",
      "caulk",
      "re-caulk",
      "waterproofing",
      "joint sealant",
    ],
  },
  {
    rt: "BUILDING-ENVELOP-WS",
    keywords: [
      "weather stripping",
      "weatherstrip",
      "door seal",
      "window seal",
      "draft",
      "draught",
      "air leak",
      "cold draft",
      "warm draft",
      "door gap",
      "window gap",
      "insulation strip",
      "door bottom seal",
    ],
  },
  {
    rt: "CARD ACCESS - LL - PROGRAMMING",
    keywords: [
      "card access programming",
      "landlord programming",
      "access programming",
      "ll programming",
      "reprogram card access",
      "access system programming",
      "add card access",
      "update card access",
      "program access card",
      "landlord access system",
    ],
  },
  {
    rt: "CARD ACCESS - LL - READER REPAIRS",
    keywords: [
      "card reader repair",
      "landlord card reader",
      "ll reader repair",
      "reader broken",
      "reader malfunction",
      "card reader not working",
      "access reader broken",
      "landlord reader repair",
      "reader fault",
      "card reader damaged",
    ],
  },
  {
    rt: "CARD ACCESS - PAN",
    keywords: [
      "card access panel",
      "access panel",
      "pan",
      "panic button",
      "access control panel",
      "door panel",
      "panel not working",
      "card panel broken",
      "access panel fault",
      "intercom panel",
    ],
  },
  {
    rt: "CARD ACCESS - TEN - NEW READER",
    keywords: [
      "new card reader",
      "tenant card reader",
      "new access reader",
      "install card reader",
      "install reader",
      "additional reader",
      "card reader installation",
      "new access point",
      "tenant access reader",
      "need card reader",
    ],
  },
  {
    rt: "CARD ACCESS - TEN - PROGRAMMING",
    keywords: [
      "tenant card programming",
      "tenant access programming",
      "program tenant card",
      "tenant access setup",
      "tenant card setup",
      "tenant programming",
      "update tenant access",
      "tenant card access",
    ],
  },
  {
    rt: "CARD ACCESS - TEN - READER REPAIRS",
    keywords: [
      "tenant reader repair",
      "tenant card reader broken",
      "tenant reader fault",
      "tenant access reader not working",
      "tenant reader malfunction",
      "fix tenant reader",
      "tenant card reader repair",
    ],
  },
  {
    rt: "CARPET - COMMON - CLEAN ENTIRE",
    keywords: [
      "carpet cleaning",
      "clean entire carpet",
      "common area carpet",
      "full carpet clean",
      "hallway carpet",
      "lobby carpet clean",
      "common carpet cleaning",
      "deep carpet clean",
    ],
  },
  {
    rt: "CARPET - COMMON - OTHER",
    keywords: [
      "carpet issue",
      "carpet common area",
      "common carpet problem",
      "carpet hallway",
      "corridor carpet",
      "carpet other",
    ],
  },
  {
    rt: "CARPET - TENANT - CLEAN ENTIRE",
    keywords: [
      "tenant carpet cleaning",
      "clean office carpet",
      "full office carpet clean",
      "carpet shampoo",
      "office carpet deep clean",
      "tenant carpet full clean",
    ],
  },
  {
    rt: "CARPET - TENANT - OTHER",
    keywords: [
      "tenant carpet issue",
      "office carpet problem",
      "carpet repair tenant",
      "carpet fraying",
      "carpet lifting",
      "carpet loose",
    ],
  },
  {
    rt: "CARPET - TENANT - SPOT CLEAN",
    keywords: [
      "carpet spot clean",
      "carpet stain",
      "stained carpet",
      "spot clean",
      "carpet spill",
      "carpet mark",
      "carpet soiled",
      "dirty carpet spot",
    ],
  },
  {
    rt: "CASH/MONEY COUNTER",
    keywords: [
      "cash counter",
      "money counter",
      "bill counter",
      "note counter",
      "cash counting machine",
      "money counting machine",
      "currency counter",
      "cash counter broken",
      "money counter not working",
    ],
  },
  {
    rt: "CASHDRAWER/AHU - AHU DRAWER REPAIRS",
    keywords: [
      "ahu drawer",
      "ahu drawer repair",
      "cash drawer repair",
      "ahu repair",
      "drawer broken",
      "cash handling unit repair",
      "ahu unit repair",
    ],
  },
  {
    rt: "CASHDRAWER/AHU - AHU NEW",
    keywords: [
      "new ahu",
      "ahu new",
      "new cash handling unit",
      "ahu replacement",
      "replace ahu",
      "install ahu",
    ],
  },
  {
    rt: "CASHDRAWER/AHU - CASHDRAWER LOCK",
    keywords: [
      "cashdrawer lock",
      "cash drawer lock",
      "cash drawer locked",
      "cash drawer won't open",
      "drawer lock broken",
      "cash drawer lock repair",
    ],
  },
  {
    rt: "CASHDRAWER/AHU - CASHTRAY LOCK",
    keywords: [
      "cashtray lock",
      "cash tray lock",
      "cash tray locked",
      "tray lock broken",
      "cash tray won't open",
      "cashtray lock repair",
    ],
  },
  {
    rt: "CASHDRAWER/AHU - CASHTRAY NEW",
    keywords: [
      "new cashtray",
      "new cash tray",
      "replace cashtray",
      "cashtray replacement",
      "cash tray new",
      "install cash tray",
    ],
  },
  {
    rt: "CDU REPAIRS",
    keywords: [
      "cdu repair",
      "cdu broken",
      "cash dispense unit",
      "cash dispensing unit",
      "cdu not working",
      "cdu fault",
      "currency dispense unit repair",
    ],
  },
  {
    rt: "CLEANING - ENTIRE",
    keywords: [
      "full cleaning",
      "clean entire",
      "complete cleaning",
      "full clean",
      "entire office clean",
      "whole building clean",
      "deep clean",
      "thorough cleaning",
    ],
  },
  {
    rt: "CLEANING - LIMITED",
    keywords: [
      "limited cleaning",
      "partial clean",
      "spot cleaning",
      "targeted cleaning",
      "specific area clean",
      "small cleaning job",
    ],
  },
  {
    rt: "CLEANING - PAN",
    keywords: [
      "cleaning pan",
      "cleaning panel",
      "cleaning request pan",
      "pan cleaning",
      "general cleaning pan",
    ],
  },
  {
    rt: "CLEANING - SUPPLIES - PAN",
    keywords: [
      "cleaning supplies",
      "need cleaning supplies",
      "cleaning products",
      "soap refill",
      "paper towel refill",
      "toilet paper refill",
      "cleaning supply request",
      "out of supplies",
      "hand sanitizer refill",
    ],
  },
  {
    rt: "CLOSURE - WEATHER",
    keywords: [
      "weather closure",
      "closed due to weather",
      "storm closure",
      "weather related closure",
      "branch closed weather",
      "snow closure",
      "flood closure",
      "weather emergency",
      "office closed weather",
    ],
  },
  {
    rt: "COMPUTERS - NEW/REPAIR",
    keywords: [
      "computer repair",
      "new computer",
      "pc broken",
      "computer not working",
      "laptop broken",
      "new laptop",
      "monitor broken",
      "computer install",
      "desktop repair",
      "computer replacement",
      "it equipment",
    ],
  },
  {
    rt: "CONTROLS",
    keywords: [
      "controls",
      "building controls",
      "energy controls",
      "ee controls",
      "control system",
      "building automation",
      "control panel",
      "system controls",
    ],
  },
  {
    rt: "COPIER / FAX - NEW",
    keywords: [
      "new copier",
      "new fax",
      "new printer",
      "copier request",
      "fax machine new",
      "new photocopier",
      "new multifunction printer",
      "mfp new",
      "need copier",
    ],
  },
  {
    rt: "COPIER / FAX - REPAIR",
    keywords: [
      "copier broken",
      "fax broken",
      "printer broken",
      "copier not working",
      "fax not working",
      "photocopier repair",
      "copier jam",
      "paper jam",
      "copier fault",
      "mfp broken",
      "printer repair",
    ],
  },
  {
    rt: "COURIER BOX - LOCK",
    keywords: [
      "courier box lock",
      "courier box locked",
      "delivery box lock",
      "courier lock broken",
      "courier box won't open",
    ],
  },
  {
    rt: "COURIER BOX - LOCK - EXTERNAL",
    keywords: [
      "external courier box lock",
      "outside courier box lock",
      "external delivery box lock",
      "courier box external lock broken",
    ],
  },
  {
    rt: "COURIER BOX - LOCK - INTERNAL",
    keywords: [
      "internal courier box lock",
      "inside courier box lock",
      "internal delivery box lock",
      "courier box internal lock broken",
    ],
  },
  {
    rt: "COURIER BOX - REPAIR",
    keywords: [
      "courier box repair",
      "delivery box repair",
      "courier box broken",
      "courier box damaged",
      "fix courier box",
      "courier box not working",
    ],
  },
  {
    rt: "DISASTER RESPONSE - CLEANING",
    keywords: [
      "disaster cleaning",
      "flood cleanup",
      "fire cleanup",
      "emergency clean",
      "disaster recovery cleaning",
      "storm damage cleaning",
      "water damage cleanup",
    ],
  },
  {
    rt: "DISASTER RESPONSE - OTHER",
    keywords: [
      "disaster response",
      "emergency response",
      "disaster recovery",
      "incident response",
      "crisis response",
      "natural disaster",
    ],
  },
  {
    rt: "DOOR REPAIR-COMMON - DOOR OPERATOR",
    keywords: [
      "automatic door",
      "door operator",
      "auto door broken",
      "door opener broken",
      "automatic door not working",
      "common door operator",
      "door motor",
      "door actuator",
      "sliding door broken",
    ],
  },
  {
    rt: "DOOR REPAIR-COMMON - GLASS MANUAL",
    keywords: [
      "glass door broken",
      "glass door repair",
      "manual glass door",
      "common glass door",
      "glass door cracked",
      "glass door handle broken",
      "glass door hinge",
      "glass panel broken",
    ],
  },
  {
    rt: "DOOR REPAIR-COMMON - O/HEAD / GRILL",
    keywords: [
      "overhead door",
      "overhead grill",
      "grill door",
      "rollup door",
      "roll up door",
      "overhead door broken",
      "grill broken",
      "overhead grill repair",
      "security grill",
    ],
  },
  {
    rt: "DOOR REPAIR-TENANT - ALARMED DOOR",
    keywords: [
      "alarmed door",
      "door alarm",
      "door alarm going off",
      "alarm door broken",
      "alarmed door repair",
      "emergency exit alarm",
      "fire door alarm",
    ],
  },
  {
    rt: "DOOR REPAIR-TENANT - DOOR OPERATOR",
    keywords: [
      "tenant automatic door",
      "tenant door operator",
      "tenant auto door broken",
      "tenant door opener",
      "tenant door motor",
      "tenant sliding door",
    ],
  },
  {
    rt: "DOOR REPAIR-TENANT - EXTERIOR",
    keywords: [
      "exterior door repair",
      "outside door broken",
      "tenant exterior door",
      "front door broken",
      "back door broken",
      "external door repair",
      "exterior door not closing",
    ],
  },
  {
    rt: "DOOR REPAIR-TENANT - GLASS MANUAL",
    keywords: [
      "tenant glass door",
      "tenant glass door broken",
      "office glass door",
      "glass office door",
      "glass door tenant",
      "tenant glass door repair",
    ],
  },
  {
    rt: "DOOR REPAIR-TENANT - GRILL",
    keywords: [
      "tenant grill",
      "security grill tenant",
      "grill door tenant",
      "tenant grill broken",
      "tenant grill repair",
      "office grill door",
    ],
  },
  {
    rt: "DOOR REPAIR-TENANT - INTERIOR",
    keywords: [
      "interior door repair",
      "inside door broken",
      "interior door tenant",
      "office door broken",
      "interior door not closing",
      "room door broken",
      "interior door hinge",
      "interior door handle",
    ],
  },
  {
    rt: "DOOR REPAIR-TENANT - MAN TRAP",
    keywords: [
      "man trap",
      "mantrap",
      "man trap door",
      "man trap broken",
      "security vestibule",
      "man trap not working",
      "double door security",
      "airlock door",
    ],
  },
  {
    rt: "DOOR REPAIR-TENANT - O/HEAD",
    keywords: [
      "tenant overhead door",
      "tenant rollup door",
      "tenant overhead door broken",
      "overhead door tenant",
      "roll up door tenant",
      "tenant garage door",
    ],
  },
  {
    rt: "DOOR REPAIR-TENANT - REVOLVING",
    keywords: [
      "revolving door",
      "revolving door broken",
      "revolving door stuck",
      "revolving door repair",
      "rotating door",
      "spinning door",
    ],
  },
  {
    rt: "DYE-PACKS - REPLACEMENT",
    keywords: [
      "dye pack",
      "dye packs",
      "dye pack replacement",
      "replace dye pack",
      "security dye pack",
      "dye pack expired",
      "new dye pack",
    ],
  },
  {
    rt: "ELEC-ELECTRICAL",
    keywords: [
      "electrical",
      "electrical issue",
      "electrical problem",
      "ee electrical",
      "electrical fault",
      "wiring issue",
      "electrical work",
    ],
  },
  {
    rt: "ELEC-TIMER-INSTALL",
    keywords: [
      "timer installation",
      "install timer",
      "electrical timer",
      "timer install",
      "ee timer",
      "light timer",
      "timer switch install",
    ],
  },
  {
    rt: "ELECTRICAL - CABLE NEW",
    keywords: [
      "new cable",
      "new electrical cable",
      "cable installation",
      "run cable",
      "new wiring",
      "cable new",
      "install cable",
    ],
  },
  {
    rt: "ELECTRICAL - CABLE REPAIR",
    keywords: [
      "cable repair",
      "damaged cable",
      "cable broken",
      "cable fault",
      "electrical cable repair",
      "wiring repair",
    ],
  },
  {
    rt: "ELECTRICAL - INSTALL",
    keywords: [
      "electrical install",
      "electrical installation",
      "new electrical",
      "install electrical",
      "new outlet install",
      "new socket install",
      "electrical setup",
    ],
  },
  {
    rt: "ELECTRICAL - POWER OUTAGE",
    keywords: [
      "power outage",
      "no power",
      "power cut",
      "power failure",
      "electricity out",
      "power down",
      "blackout",
      "power loss",
    ],
  },
  {
    rt: "ELECTRICAL - POWER OUTAGE ENTIRE",
    keywords: [
      "complete power outage",
      "entire power outage",
      "full power cut",
      "whole building no power",
      "total blackout",
      "all power out",
      "building wide power outage",
    ],
  },
  {
    rt: "ELECTRICAL - REPAIR",
    keywords: [
      "electrical repair",
      "fix electrical",
      "electrical broken",
      "electrical not working",
      "electrical fault repair",
      "wiring broken",
    ],
  },
  {
    rt: "ELECTRICAL - UPS/DIESEL GENERATOR",
    keywords: [
      "ups",
      "diesel generator",
      "generator",
      "ups broken",
      "generator fault",
      "backup power",
      "uninterruptible power supply",
      "generator not starting",
      "ups alarm",
      "ups fault",
      "generator repair",
    ],
  },
  {
    rt: "ELEVATORS - COMMON - REPAIRS",
    keywords: [
      "elevator repair",
      "lift repair",
      "common elevator broken",
      "elevator not working",
      "elevator maintenance",
      "lift broken",
      "common lift repair",
    ],
  },
  {
    rt: "ELEVATORS - TENANT - EMERG/STUCK",
    keywords: [
      "elevator stuck",
      "lift stuck",
      "stuck in elevator",
      "stuck in lift",
      "elevator emergency",
      "lift emergency",
      "trapped in elevator",
      "elevator not moving",
      "person stuck elevator",
    ],
  },
  {
    rt: "ELEVATORS - TENANT - REPAIRS",
    keywords: [
      "tenant elevator repair",
      "tenant lift repair",
      "office elevator broken",
      "tenant elevator not working",
      "elevator door broken",
      "elevator button broken",
      "elevator slow",
      "elevator noise",
    ],
  },
  {
    rt: "EMERGENCY LIGHTING - INSPECTION",
    keywords: [
      "emergency lighting inspection",
      "inspect emergency lights",
      "emergency light check",
      "exit light inspection",
      "battery backup light check",
      "emergency lighting test",
    ],
  },
  {
    rt: "EMERGENCY LIGHTING - REPAIRS",
    keywords: [
      "emergency lighting repair",
      "emergency light broken",
      "exit light broken",
      "emergency light not working",
      "battery backup light broken",
      "emergency light fault",
    ],
  },
  {
    rt: "ENERGY-EFFICIENCY",
    keywords: [
      "energy efficiency",
      "energy saving",
      "ee",
      "reduce energy",
      "energy audit",
      "energy consumption",
      "green energy",
      "sustainability",
      "energy waste",
      "energy reduction",
    ],
  },
  {
    rt: "ENVIRONMENTAL - MOULD/ASBESTOS/IAQ",
    keywords: [
      "mould",
      "mold",
      "asbestos",
      "iaq",
      "indoor air quality",
      "environmental issue",
      "mould on wall",
      "asbestos inspection",
      "air quality test",
      "environmental hazard",
      "toxic material",
    ],
  },
  {
    rt: "EXT REP COMM - BRICK/FOUNDATION",
    keywords: [
      "brick repair",
      "foundation repair",
      "common brick",
      "cracked brick",
      "foundation crack",
      "exterior brick",
      "masonry repair",
      "brickwork",
    ],
  },
  {
    rt: "EXT REP COMM - OTHER",
    keywords: [
      "exterior repair common",
      "common area exterior",
      "outside repair common",
    ],
  },
  {
    rt: "EXT REP COMM - PK LOT - LINE",
    keywords: [
      "parking lot line",
      "parking line painting",
      "parking lines faded",
      "repaint parking lines",
      "common parking lines",
      "lot line marking",
    ],
  },
  {
    rt: "EXT REP COMM - PK LOT REPAIR",
    keywords: [
      "parking lot repair",
      "common parking lot",
      "parking lot pothole",
      "parking lot crack",
      "parking lot damage",
    ],
  },
  {
    rt: "EXT REP TEN - BRICK/FOUNDATION",
    keywords: [
      "tenant brick repair",
      "tenant foundation",
      "tenant exterior brick",
      "tenant masonry",
      "cracked foundation tenant",
    ],
  },
  {
    rt: "EXT REP TEN - OTHER",
    keywords: [
      "tenant exterior repair",
      "tenant outside repair",
      "exterior tenant other",
    ],
  },
  {
    rt: "EXT REP TEN - PK LOT - LINE",
    keywords: [
      "tenant parking lines",
      "tenant lot line",
      "tenant parking line painting",
      "repaint tenant parking",
    ],
  },
  {
    rt: "EXT REP TEN - PK LOT - PAVE",
    keywords: [
      "tenant paving",
      "parking lot paving tenant",
      "tenant pavement",
      "repave parking tenant",
      "asphalt tenant",
    ],
  },
  {
    rt: "EXT REP TEN - PK LOT - REPAIR",
    keywords: [
      "tenant parking lot repair",
      "tenant lot pothole",
      "tenant lot crack",
      "tenant parking lot damaged",
    ],
  },
  {
    rt: "FIRE EQUIPMENT - INSPECTION",
    keywords: [
      "fire inspection",
      "fire equipment check",
      "fire extinguisher inspection",
      "sprinkler inspection",
      "fire alarm inspection",
      "fire safety check",
      "annual fire inspection",
    ],
  },
  {
    rt: "FIRE EQUIPMENT - PURCHASE",
    keywords: [
      "fire equipment purchase",
      "buy fire extinguisher",
      "new fire extinguisher",
      "purchase fire equipment",
      "new fire safety equipment",
    ],
  },
  {
    rt: "FIRE EQUIPMENT - REPAIRS",
    keywords: [
      "fire equipment repair",
      "fire extinguisher repair",
      "sprinkler repair",
      "fire alarm repair",
      "fire safety repair",
      "fire panel repair",
    ],
  },
  {
    rt: "FIRE EQUIPMENT - SUPPRESSION",
    keywords: [
      "fire suppression",
      "fire suppression system",
      "suppression system repair",
      "halon system",
      "co2 suppression",
      "fire suppression broken",
    ],
  },
  {
    rt: "FLOOR REP COMM - CARPET",
    keywords: [
      "common carpet repair",
      "hallway carpet repair",
      "lobby carpet repair",
      "common area carpet damaged",
      "carpet worn common",
    ],
  },
  {
    rt: "FLOOR REP COMM - CERAMIC/TILE",
    keywords: [
      "tile repair common",
      "ceramic tile common",
      "common area tile broken",
      "lobby tile",
      "hallway tile cracked",
      "floor tile common repair",
    ],
  },
  {
    rt: "FLOOR REP COMM - OTHER",
    keywords: [
      "common floor repair",
      "floor damage common",
      "common area floor",
    ],
  },
  {
    rt: "FLOOR REP TEN - CARPET",
    keywords: [
      "tenant carpet repair",
      "office carpet damaged",
      "carpet worn tenant",
      "carpet replacement tenant",
      "office floor carpet",
    ],
  },
  {
    rt: "FLOOR REP TEN - CERAMIC/TILE",
    keywords: [
      "tenant tile repair",
      "office tile broken",
      "tenant ceramic tile",
      "office floor tile cracked",
      "tile replacement tenant",
    ],
  },
  {
    rt: "FLOOR REP TEN - OTHER",
    keywords: [
      "tenant floor repair",
      "office floor damage",
      "floor damage tenant",
    ],
  },
  {
    rt: "FM - OUT OF SCOPE",
    keywords: [
      "out of scope",
      "not fm scope",
      "outside scope",
      "not facilities",
    ],
  },
  {
    rt: "FURNITURE LOCKS - FIREPROOF",
    keywords: [
      "fireproof furniture lock",
      "fireproof cabinet lock",
      "fire safe lock",
      "fireproof safe",
      "fire rated cabinet",
      "fireproof lock",
    ],
  },
  {
    rt: "FURNITURE LOCKS - INSTALL/REPAIRS/KEYS",
    keywords: [
      "furniture lock",
      "install furniture lock",
      "furniture lock repair",
      "furniture key",
      "lost furniture key",
      "desk lock",
      "cabinet lock",
      "filing cabinet lock",
      "furniture lock broken",
      "new furniture key",
    ],
  },
];
