export const REQUEST_TYPE_KEYWORDS: { rt: string; keywords: string[] }[] = [
  {
    rt: "ELEVATOR - ISSUE",
    keywords: [
      "elevator",
      "lift",
      "stuck",
      "cab",
      "elevator button",
      "floor button",
      "door won't open",
      "elevator door",
      "elevator noise",
      "elevator smell",
      "elevator not working",
      "elevator out of service",
      "elevator broken",
      "elevator shaking",
      "elevator slow",
      "elevator alarm",
      "elevator panel",
    ],
  },
  {
    rt: "PLUMBING - ISSUE",
    keywords: [
      "water",
      "leak",
      "leaking",
      "pipe",
      "burst pipe",
      "drain",
      "drainage",
      "toilet",
      "toilet clogged",
      "toilet overflowing",
      "toilet broken",
      "sink",
      "sink blocked",
      "flood",
      "flooding",
      "tap",
      "faucet",
      "dripping",
      "sewage",
      "sewer",
      "clog",
      "blocked drain",
      "water pressure",
      "no water",
      "hot water",
      "cold water",
      "water stain",
      "water damage",
      "puddle",
      "moisture",
      "damp",
      "wet floor",
      "shower",
      "shower drain",
      "urinal",
    ],
  },
  {
    rt: "ELECTRICAL - ISSUE",
    keywords: [
      "light",
      "lights",
      "lighting",
      "light out",
      "bulb",
      "bulb blown",
      "power",
      "no power",
      "power outage",
      "power cut",
      "outlet",
      "socket",
      "plug",
      "breaker",
      "circuit breaker",
      "tripped",
      "electric",
      "electrical",
      "flicker",
      "flickering",
      "blown fuse",
      "fuse",
      "wiring",
      "switch",
      "light switch",
      "power strip",
      "extension cord",
      "sparks",
      "burning smell",
      "buzzing",
      "humming",
      "generator",
      "ups",
      "emergency light",
      "exit sign",
    ],
  },
  {
    rt: "HVAC - ISSUE",
    keywords: [
      "air",
      "hvac",
      "heating",
      "heat",
      "cooling",
      "cool",
      "ac",
      "a/c",
      "air conditioning",
      "air conditioner",
      "ventilation",
      "vent",
      "duct",
      "temperature",
      "too hot",
      "too cold",
      "hot",
      "cold",
      "thermostat",
      "fan",
      "blower",
      "filter",
      "air filter",
      "stuffy",
      "humid",
      "humidity",
      "condensation",
      "freezing",
      "overheating",
      "no airflow",
      "airflow",
      "boiler",
      "radiator",
      "chiller",
      "heat pump",
      "exhaust fan",
    ],
  },
  {
    rt: "CLEANING - REQUEST",
    keywords: [
      "clean",
      "cleaning",
      "dirty",
      "dirt",
      "filthy",
      "spill",
      "spillage",
      "trash",
      "garbage",
      "rubbish",
      "waste",
      "bin",
      "bin full",
      "overflowing bin",
      "mess",
      "mop",
      "sweep",
      "sweeping",
      "vacuum",
      "sanitize",
      "disinfect",
      "odor",
      "smell",
      "bad smell",
      "stench",
      "restroom dirty",
      "bathroom dirty",
      "grease",
      "grime",
      "dust",
      "dusty",
      "cobweb",
      "insect",
      "pest",
      "rodent",
      "mouse",
      "rat",
      "cockroach",
      "ants",
    ],
  },
  {
    rt: "SECURITY - ISSUE",
    keywords: [
      "security",
      "lock",
      "locked out",
      "unlock",
      "key",
      "lost key",
      "access",
      "access denied",
      "badge",
      "id badge",
      "card",
      "key card",
      "door",
      "door not closing",
      "door not locking",
      "intruder",
      "suspicious person",
      "camera",
      "cctv",
      "alarm",
      "alarm going off",
      "unauthorized",
      "break in",
      "card reader",
      "intercom",
      "gate",
      "barrier",
      "turnstile",
      "safe",
      "theft",
      "stolen",
      "vandalism",
      "trespassing",
    ],
  },
  {
    rt: "CARPENTRY - REPAIR",
    keywords: [
      "door",
      "door broken",
      "door stuck",
      "door hinge",
      "door handle",
      "window",
      "window broken",
      "window stuck",
      "window latch",
      "cabinet",
      "cabinet door",
      "shelf",
      "shelving",
      "furniture",
      "broken furniture",
      "hinge",
      "handle",
      "frame",
      "wood",
      "wooden",
      "repair",
      "crack",
      "cracked",
      "splinter",
      "warped",
      "loose",
      "desk",
      "chair",
      "table",
      "partition",
      "cubicle",
      "drawer",
      "lock mechanism",
      "door closer",
      "floor board",
      "squeaky",
    ],
  },
  {
    rt: "PAINTING - REQUEST",
    keywords: [
      "paint",
      "painting",
      "repaint",
      "wall",
      "walls",
      "ceiling",
      "peeling",
      "peeling paint",
      "flaking",
      "chipping",
      "stain",
      "stained",
      "graffiti",
      "discolored",
      "discolouration",
      "faded",
      "fading",
      "scuff",
      "scuff mark",
      "scratch",
      "scratched wall",
      "mold on wall",
      "mildew",
      "damp patch",
      "water mark",
      "touch up",
    ],
  },
  {
    rt: "PEST CONTROL - REQUEST",
    keywords: [
      "pest",
      "pest control",
      "insect",
      "bug",
      "bugs",
      "cockroach",
      "roach",
      "ant",
      "ants",
      "mouse",
      "mice",
      "rat",
      "rats",
      "rodent",
      "rodents",
      "spider",
      "wasp",
      "bee",
      "beehive",
      "nest",
      "infestation",
      "termite",
      "fly",
      "flies",
      "mosquito",
      "mosquitoes",
      "bed bug",
      "flea",
    ],
  },
  {
    rt: "FURNITURE - REQUEST",
    keywords: [
      "furniture",
      "chair",
      "chairs",
      "desk",
      "desks",
      "table",
      "tables",
      "sofa",
      "couch",
      "bench",
      "cabinet",
      "filing cabinet",
      "bookshelf",
      "whiteboard",
      "projector screen",
      "monitor stand",
      "footrest",
      "ergonomic",
      "new chair",
      "replace chair",
      "broken chair",
      "broken desk",
      "missing furniture",
      "additional furniture",
    ],
  },
  {
    rt: "WASTE MANAGEMENT - REQUEST",
    keywords: [
      "waste",
      "waste disposal",
      "recycling",
      "recycle",
      "bin",
      "bins",
      "dumpster",
      "skip",
      "hazardous waste",
      "chemical disposal",
      "e-waste",
      "electronic waste",
      "paper shredding",
      "confidential waste",
      "compost",
      "landfill",
      "garbage collection",
      "rubbish collection",
      "waste bin full",
      "overflowing",
      "litter",
    ],
  },
  {
    rt: "GENERAL MAINTENANCE - REQUEST",
    keywords: [
      "maintenance",
      "general maintenance",
      "repair",
      "fix",
      "broken",
      "not working",
      "out of order",
      "damaged",
      "worn out",
      "replace",
      "replacement",
      "install",
      "installation",
      "inspect",
      "inspection",
      "service",
      "routine",
      "preventive",
      "worn",
      "deteriorating",
    ],
  },
];
